server:
  port: 8099
  context-path: /


spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.14.201:3306/db_jxc?verifyServerCertificate=false&useSSL=true
    username: root
    password: Hadoop8341@
#    mvc:
#      static-path-pattern: /static/**
#      view:
#        prefix: classpath:/templates/
#        suffix: .html

  jpa:
    hibernate.ddl-auto: update
    show-sql: true
