server:
  port: 8099
  context-path: /


spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url:
    username:
    password:
#    mvc:
#      static-path-pattern: /static/**
#      view:
#        prefix: classpath:/templates/
#        suffix: .html

  jpa:
    hibernate.ddl-auto: update
    show-sql: true
